var categories = [
	'Object',
	'Travel',
	'Emotion',
	'Clothes',
	'Flag',	
	'Food & Drink',
	'Food',
	'Drink',
	'Fruit',
	'Bread',
	'Meat',
	'Vegetable',
	'Animal & Nature',
	'Animal',
	'Nature'
]

var emojis = [
[ '💌', [ 'Object' ], "Love Letter" ],
[ '🕳️', [ 'Object' ], "Hole" ],
[ '💣', [ 'Object' ], "Bomb" ],
[ '🛀', [ 'Object' ], "Person Taking Bath" ],
[ '🛌', [ 'Object' ], "Person in Bed" ],
[ '🔪', [ 'Object', 'Food & Drink' ], "Kitchen Knife" ],
[ '🏺', [ 'Object' ], "Amphora" ],
[ '🗺️', [ 'Travel', 'Object' ], "World Map" ],
[ '🧭', [ 'Travel', 'Object' ], "Compass" ],
[ '🧱', [ 'Object' ], "Brick" ],
[ '💈', [ 'Object' ], "Barber Pole" ],
[ '🦽', [ 'Travel', 'Object' ], "Manual Wheelchair" ],
[ '🛢️', [ 'Object' ], "Oil Drum" ],
[ '🛎️', [ 'Object' ], "Bellhop Bell" ],
[ '🧳', [ 'Travel', 'Object' ], "Luggage" ],
[ '⏳', [ 'Object' ], "Hourglass Not Done" ],
[ '⌚', [ 'Object' ], "Watch" ],
[ '⏰', [ 'Object' ], "Alarm Clock" ],
[ '⏱️', [ 'Object' ], "Stopwatch" ],
[ '🌡️', [ 'Object' ], "Thermometer" ],
[ '🧨', [ 'Object' ], "Firecracker" ],
[ '🎈', [ 'Object' ], "Balloon" ],
[ '🎉', [ 'Object' ], "Party Popper" ],
[ '🎎', [ 'Object' ], "Japanese Dolls" ],
[ '🎀', [ 'Object', 'Clothes' ], "Ribbon" ],
[ '🎁', [ 'Object' ], "Wrapped Gift" ],
[ '🤿', [ 'Object' ], "Diving Mask" ],
[ '🪀', [ 'Object' ], "Yo-Yo" ],
[ '🪁', [ 'Object' ], "Kite" ],
[ '🔮', [ 'Object' ], "Crystal Ball" ],
[ '🕹️', [ 'Object' ], "Joystick" ],
[ '🧸', [ 'Object' ], "Teddy Bear" ],
[ '🖼️', [ 'Object' ], "Framed Picture" ],
[ '🧵', [ 'Object', 'Clothes' ], "Thread" ],
[ '🧶', [ 'Object', 'Clothes' ], "Yarn" ],
[ '🛍️', [ 'Object' ], "Shopping Bags" ],
[ '📿', [ 'Object', 'Clothes' ], "Prayer Beads" ],
[ '💎', [ 'Object' ], "Gem Stone" ],
[ '🎙️', [ 'Object' ], "Studio Microphone" ],
[ '📻', [ 'Object' ], "Radio" ],
[ '📱', [ 'Object' ], "Mobile Phone" ],
[ '☎️', [ 'Object' ], "Telephone" ],
[ '🔋', [ 'Object' ], "Battery" ],
[ '🔌', [ 'Object' ], "Electric Plug" ],
[ '💻', [ 'Object' ], "Laptop" ],
[ '🖨️', [ 'Object' ], "Printer" ],
[ '⌨️', [ 'Object' ], "Keyboard" ],
[ '🖱️', [ 'Object' ], "Computer Mouse" ],
[ '💾', [ 'Object' ], "Floppy Disk" ],
[ '💿', [ 'Object' ], "Optical Disk" ],
[ '🧮', [ 'Object' ], "Abacus" ],
[ '🎥', [ 'Object' ], "Movie Camera" ],
[ '🎞️', [ 'Object' ], "Film Frames" ],
[ '📽️', [ 'Object' ], "Film Projector" ],
[ '📺', [ 'Object' ], "Television" ],
[ '📸', [ 'Object' ], "Camera with Flash" ],
[ '📹', [ 'Object' ], "Video Camera" ],
[ '📼', [ 'Object' ], "Videocassette" ],
[ '🔍', [ 'Object' ], "Magnifying Glass Tilted Left" ],
[ '🕯️', [ 'Object' ], "Candle" ],
[ '💡', [ 'Object' ], "Light Bulb" ],
[ '🔦', [ 'Object' ], "Flashlight" ],
[ '📚', [ 'Object' ], "Books" ],
[ '📃', [ 'Object' ], "Page with Curl" ],
[ '📜', [ 'Object' ], "Scroll" ],
[ '📰', [ 'Object' ], "Newspaper" ],
[ '🏷️', [ 'Object' ], "Label" ],
[ '💰', [ 'Object' ], "Money Bag" ],
[ '💷', [ 'Object' ], "Pound Banknote" ],
[ '💳', [ 'Object' ], "Credit Card" ],
[ '✉️', [ 'Object' ], "Envelope" ],
[ '📦', [ 'Object' ], "Package" ],
[ '📬', [ 'Object' ], "Open Mailbox with Raised Flag" ],
[ '🗳️', [ 'Object' ], "Ballot Box with Ballot" ],
[ '✏️', [ 'Object' ], "Pencil" ],
[ '🖋️', [ 'Object' ], "Fountain Pen" ],
[ '🖍️', [ 'Object' ], "Crayon" ],
[ '📅', [ 'Object' ], "Calendar" ],
[ '📌', [ 'Object' ], "Pushpin" ],
[ '📎', [ 'Object' ], "Paperclip" ],
[ '📏', [ 'Object' ], "Straight Ruler" ],
[ '📐', [ 'Object' ], "Triangular Ruler" ],
[ '✂️', [ 'Object' ], "Scissors" ],
[ '🗄️', [ 'Object' ], "File Cabinet" ],
[ '🗑️', [ 'Object' ], "Wastebasket" ],
[ '🔐', [ 'Object' ], "Locked with Key" ],
[ '🔑', [ 'Object' ], "Key" ],
[ '🔨', [ 'Object' ], "Hammer" ],
[ '🪓', [ 'Object' ], "Axe" ],
[ '⛏️', [ 'Object' ], "Pick" ],
[ '🗡️', [ 'Object' ], "Dagger" ],
[ '🔫', [ 'Object' ], "Pistol" ],
[ '🛡️', [ 'Object' ], "Shield" ],
[ '🔧', [ 'Object' ], "Wrench" ],
[ '⚙️', [ 'Object' ], "Gear" ],
[ '⚖️', [ 'Object' ], "Balance Scale" ],
[ '🦯', [ 'Object' ], "White Cane" ],
[ '⛓️', [ 'Object' ], "Chains" ],
[ '🧰', [ 'Object' ], "Toolbox" ],
[ '🧲', [ 'Object' ], "Magnet" ],
[ '⚗️', [ 'Object' ], "Alembic" ],
[ '🧪', [ 'Object' ], "Test Tube" ],
[ '🧫', [ 'Object' ], "Petri Dish" ],
[ '🧬', [ 'Object' ], "DNA" ],
[ '🔬', [ 'Object' ], "Microscope" ],
[ '🔭', [ 'Object' ], "Telescope" ],
[ '📡', [ 'Object' ], "Satellite Antenna" ],
[ '💊', [ 'Object' ], "Pill" ],
[ '🩹', [ 'Object' ], "Adhesive Bandage" ],
[ '🩺', [ 'Object' ], "Stethoscope" ],
[ '🚪', [ 'Object' ], "Door" ],
[ '🛏️', [ 'Object' ], "Bed" ],
[ '🪑', [ 'Object' ], "Chair" ],
[ '🚿', [ 'Object' ], "Shower" ],
[ '🛁', [ 'Object' ], "Bathtub" ],
[ '🧷', [ 'Object' ], "Safety Pin" ],
[ '🧹', [ 'Object' ], "Broom" ],
[ '🧺', [ 'Object' ], "Basket" ],
[ '🧼', [ 'Object' ], "Soap" ],
[ '🧽', [ 'Object' ], "Sponge" ],
[ '🧯', [ 'Object' ], "Fire Extinguisher" ],
[ '🛒', [ 'Object' ], "Shopping Cart" ],
[ '🚬', [ 'Object' ], "Cigarette" ],
[ '🗿', [ 'Object' ], "Moai" ],
[ '👻', [ 'Object' ], "Ghost" ],
[ '👽', [ 'Object' ], "Alien" ],
[ '🤖', [ 'Object' ], "Robot" ],
[ '🖐️', [ 'Object' ], "Hand" ],
[ '👂', [ 'Object' ], "Ear" ],
[ '👃', [ 'Object' ], "Nose" ],
[ '🧠', [ 'Object' ], "Brain" ],
[ '🦷', [ 'Object' ], "Tooth" ],
[ '🦴', [ 'Object' ], "Bone" ],
[ '👁️', [ 'Object' ], "Eye" ],
[ '👄', [ 'Object' ], "Mouth" ],
[ '👶', [ 'Object', 'Person' ], "Baby" ],
[ '🧔', [ 'Object', 'Person' ], "Person with Beard" ],
[ '👩', [ 'Object', 'Person' ], "Woman" ],
[ '💂', [ 'Object', 'Person' ], "Guard" ],
[ '👷', [ 'Object', 'Person' ], "Construction Worker" ],
[ '👸', [ 'Object', 'Person' ], "Princess" ],
[ '🤴', [ 'Object', 'Person' ], "Prince" ],
[ '🎅', [ 'Object', 'Person' ], "Santa" ],
[ '🧛', [ 'Object', 'Person' ], "Vampire" ],
[ '🧟', [ 'Object', 'Person' ], "Zombie" ],
[ '🧗', [ 'Object', 'Person' ], "Climber" ],
[ '🤺', [ 'Object', 'Person'  ], "Fencing" ],
[ '🏇', [ 'Object', 'Person'  ], "Horse and Jockey" ],
[ '⛷️', [ 'Object', 'Person'  ], "Skier" ],
[ '🏂', [ 'Object', 'Person'  ], "Snowboarder" ],
[ '🏌️', [ 'Object', 'Person'  ], "Golfer" ],
[ '🏄', [ 'Object', 'Person' ], "Surfer" ],
[ '🏊', [ 'Object', 'Person' ], "Swimmer" ],
[ '🚣', [ 'Object', 'Person' ], "Sailor" ],
[ '🚴', [ 'Object', 'Person' ], "Cyclist" ],
[ '🤹', [ 'Object', 'Person' ], "Juggler" ],
[ '🎪', [ 'Object' ], "Circus Tent" ],
[ '🛹', [ 'Object' ], "Skateboard" ],
[ '🛶', [ 'Travel', 'Object' ], "Canoe" ],
[ '🎖️', [ 'Object' ], "Medal" ],
[ '🏆', [ 'Object' ], "Trophy" ],
[ '⚽', [ 'Object' ], "Football" ],
[ '🎾', [ 'Object' ], "Tennis" ],
[ '🎳', [ 'Object' ], "Bowling" ],
[ '⛸️', [ 'Object', 'Clothes' ], "Ice Skate" ],
[ '🎱', [ 'Object' ], "8 Ball" ],
[ '🎮', [ 'Object' ], "Video Game Controller" ],
[ '🎰', [ 'Object' ], "Slot Machine" ],
[ '🎲', [ 'Object' ], "Dice" ],
[ '🎨', [ 'Object' ], "Artist Palette" ],
[ '🎧', [ 'Object', 'Clothes' ], "Headphones" ],
[ '🎸', [ 'Object' ], "Guitar" ],
[ '🎺', [ 'Object' ], "Trumpet" ],
[ '🥁', [ 'Object' ], "Drum" ],
[ '🎬', [ 'Object' ], "Clapper Board" ],
[ '🏹', [ 'Object' ], "Bow and Arrow" ],
[ '🍇', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Grapes" ],
[ '🍉', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Watermelon" ],
[ '🍊', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Tangerine" ],
[ '🍋', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Lemon" ],
[ '🍌', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Banana" ],
[ '🍍', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Pineapple" ],
[ '🍎', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Red Apple" ],
[ '🍏', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Green Apple" ],
[ '🍐', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Pear" ],
[ '🍑', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Peach" ],
[ '🍒', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Cherries" ],
[ '🍓', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Strawberry" ],
[ '🥝', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Kiwi Fruit" ],
[ '🍅', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Tomato" ],
[ '🥥', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Coconut" ],
[ '🥑', [ 'Object', 'Food & Drink', 'Food', 'Fruit' ], "Avocado" ],
[ '🍆', [ 'Object', 'Food & Drink', 'Food', 'Vegetable' ], "Eggplant" ],
[ '🥔', [ 'Object', 'Food & Drink', 'Food', 'Vegetable' ], "Potato" ],
[ '🥕', [ 'Object', 'Food & Drink', 'Food', 'Vegetable' ], "Carrot" ],
[ '🌽', [ 'Object', 'Food & Drink', 'Food', 'Vegetable' ], "Ear of Corn" ],
[ '🌶️', [ 'Object', 'Food & Drink', 'Food', 'Vegetable' ], "Hot Pepper" ],
[ '🥒', [ 'Object', 'Food & Drink', 'Food', 'Vegetable' ], "Cucumber" ],
[ '🥬', [ 'Object', 'Food & Drink', 'Food', 'Vegetable' ], "Leafy Green" ],
[ '🥦', [ 'Object', 'Food & Drink', 'Food', 'Vegetable' ], "Broccoli" ],
[ '🧄', [ 'Object', 'Food & Drink', 'Food', 'Vegetable' ], "Garlic" ],
[ '🧅', [ 'Object', 'Food & Drink', 'Food', 'Vegetable' ], "Onion" ],
[ '🍄', [ 'Object', 'Food & Drink', 'Food', 'Vegetable' ], "Mushroom" ],
[ '🥜', [ 'Object', 'Food & Drink', 'Food' ], "Peanuts" ],
[ '🌰', [ 'Object', 'Food & Drink', 'Food' ], "Chestnut" ],
[ '🍞', [ 'Object', 'Food & Drink', 'Food', 'Bread' ], "Bread" ],
[ '🥐', [ 'Object', 'Food & Drink', 'Food', 'Bread' ], "Croissant" ],
[ '🥖', [ 'Object', 'Food & Drink', 'Food', 'Bread' ], "Baguette Bread" ],
[ '🥨', [ 'Object', 'Food & Drink', 'Food', 'Bread' ], "Pretzel" ],
[ '🥯', [ 'Object', 'Food & Drink', 'Food', 'Bread' ], "Bagel" ],
[ '🥞', [ 'Object', 'Food & Drink', 'Food', 'Bread' ], "Pancakes" ],
[ '🧇', [ 'Object', 'Food & Drink', 'Food', 'Bread' ], "Waffle" ],
[ '🧀', [ 'Object', 'Food & Drink', 'Food' ], "Cheese Wedge" ],
[ '🍖', [ 'Object', 'Food & Drink', 'Food', 'Meat' ], "Meat on Bone" ],
[ '🍗', [ 'Object', 'Food & Drink', 'Food', 'Meat' ], "Poultry Leg" ],
[ '🥩', [ 'Object', 'Food & Drink', 'Food', 'Meat' ], "Cut of Meat" ],
[ '🥓', [ 'Object', 'Food & Drink', 'Food', 'Meat' ], "Bacon" ],
[ '🍔', [ 'Object', 'Food & Drink', 'Food', 'Meat' ], "Hamburger" ],
[ '🍟', [ 'Object', 'Food & Drink', 'Food' ], "French Fries" ],
[ '🍕', [ 'Object', 'Food & Drink', 'Food', 'Bread' ], "Pizza" ],
[ '🌭', [ 'Object', 'Food & Drink', 'Food', 'Bread', 'Meat' ], "Hot Dog" ],
[ '🥪', [ 'Object', 'Food & Drink', 'Food', 'Bread' ], "Sandwich" ],
[ '🌮', [ 'Object', 'Food & Drink', 'Food', 'Bread' ], "Taco" ],
[ '🌯', [ 'Object', 'Food & Drink', 'Food', 'Bread' ], "Burrito" ],
[ '🥙', [ 'Object', 'Food & Drink', 'Food', 'Bread' ], "Stuffed Flatbread" ],
[ '🧆', [ 'Object', 'Food & Drink', 'Food' ], "Falafel" ],
[ '🥚', [ 'Object', 'Food & Drink', 'Food' ], "Egg" ],
[ '🍳', [ 'Object', 'Food & Drink', 'Food' ], "Cooking" ],
[ '🥘', [ 'Object', 'Food & Drink', 'Food' ], "Shallow Pan of Food" ],
[ '🍲', [ 'Object', 'Food & Drink', 'Food' ], "Pot of Food" ],
[ '🥣', [ 'Object', 'Food & Drink', 'Food' ], "Bowl with Spoon" ],
[ '🥗', [ 'Object', 'Food & Drink', 'Food' ], "Green Salad" ],
[ '🍿', [ 'Object', 'Food & Drink', 'Food' ], "Popcorn" ],
[ '🧈', [ 'Object', 'Food & Drink', 'Food' ], "Butter" ],
[ '🧂', [ 'Object', 'Food & Drink', 'Food' ], "Salt" ],
[ '🥫', [ 'Object', 'Food & Drink', 'Food' ], "Canned Food" ],
[ '🍱', [ 'Object', 'Food & Drink', 'Food' ], "Bento Box" ],
[ '🍜', [ 'Object', 'Food & Drink', 'Food' ], "Steaming Bowl" ],
[ '🍝', [ 'Object', 'Food & Drink', 'Food' ], "Spaghetti" ],
[ '🍣', [ 'Object', 'Food & Drink', 'Food' ], "Sushi" ],
[ '🍤', [ 'Object', 'Food & Drink', 'Food' ], "Fried Shrimp" ],
[ '🥡', [ 'Object', 'Food & Drink', 'Food' ], "Takeout Box" ],
[ '🦪', [ 'Object', 'Food & Drink', 'Food' ], "Oyster" ],
[ '🍦', [ 'Object', 'Food & Drink', 'Food' ], "Soft Ice Cream" ],
[ '🍧', [ 'Object', 'Food & Drink', 'Food' ], "Shaved Ice" ],
[ '🍨', [ 'Object', 'Food & Drink', 'Food' ], "Ice Cream" ],
[ '🍩', [ 'Object', 'Food & Drink', 'Food' ], "Doughnut" ],
[ '🍪', [ 'Object', 'Food & Drink', 'Food' ], "Cookie" ],
[ '🎂', [ 'Object', 'Food & Drink', 'Food' ], "Birthday Cake" ],
[ '🍰', [ 'Object', 'Food & Drink', 'Food' ], "Shortcake" ],
[ '🧁', [ 'Object', 'Food & Drink', 'Food' ], "Cupcake" ],
[ '🥧', [ 'Object', 'Food & Drink', 'Food' ], "Pie" ],
[ '🍫', [ 'Object', 'Food & Drink', 'Food' ], "Chocolate Bar" ],
[ '🍬', [ 'Object', 'Food & Drink', 'Food' ], "Candy" ],
[ '🍭', [ 'Object', 'Food & Drink', 'Food' ], "Lollipop" ],
[ '🍮', [ 'Object', 'Food & Drink', 'Food' ], "Custard" ],
[ '🍯', [ 'Object', 'Food & Drink', 'Food' ], "Honey Pot" ],
[ '🍼', [ 'Object', 'Food & Drink', 'Drink' ], "Baby Bottle" ],
[ '🥛', [ 'Object', 'Food & Drink', 'Drink' ], "Glass of Milk" ],
[ '☕', [ 'Object', 'Food & Drink', 'Drink' ], "Hot Beverage" ],
[ '🍵', [ 'Object', 'Food & Drink', 'Drink' ], "Teacup Without Handle" ],
[ '🍾', [ 'Object', 'Food & Drink', 'Drink' ], "Bottle with Popping Cork" ],
[ '🍷', [ 'Object', 'Food & Drink', 'Drink' ], "Wine Glass" ],
[ '🍸', [ 'Object', 'Food & Drink', 'Drink' ], "Cocktail Glass" ],
[ '🍹', [ 'Object', 'Food & Drink', 'Drink' ], "Tropical Drink" ],
[ '🍺', [ 'Object', 'Food & Drink', 'Drink' ], "Beer Mug" ],
[ '🥂', [ 'Object', 'Food & Drink', 'Drink' ], "Clinking Glasses" ],
[ '🥃', [ 'Object', 'Food & Drink', 'Drink' ], "Tumbler Glass" ],
[ '🥤', [ 'Object', 'Food & Drink', 'Drink' ], "Cup with Straw" ],
[ '🧃', [ 'Object', 'Food & Drink', 'Drink' ], "Beverage Box" ],
[ '🧊', [ 'Object', 'Food & Drink', 'Drink' ], "Ice" ],
[ '🥢', [ 'Object', 'Food & Drink' ], "Chopsticks" ],
[ '🍽️', [ 'Object', 'Food & Drink' ], "Fork and Knife with Plate" ],
[ '🥄', [ 'Object', 'Food & Drink' ], "Spoon" ],
[ '🏁', [ 'Object' ], "Chequered Flag" ],
[ '🚩', [ ], "Triangular Flag" ],
[ '🎌', [ ], "Crossed Flags" ],
[ '🏴', [ ], "Black Flag" ],
[ '🏳️', [ ], "White Flag" ],
[ '🏴‍☠️', [ 'Object' ], "Pirate Flag" ],
[ '🇦🇨', [ 'Flag' ], "Flag: Ascension Island" ],
[ '🇦🇩', [ 'Flag' ], "Flag: Andorra" ],
[ '🇦🇪', [ 'Flag' ], "Flag: United Arab Emirates" ],
[ '🇦🇫', [ 'Flag' ], "Flag: Afghanistan" ],
[ '🇦🇬', [ 'Flag' ], "Flag: Antigua & Barbuda" ],
[ '🇦🇮', [ 'Flag' ], "Flag: Anguilla" ],
[ '🇦🇱', [ 'Flag' ], "Flag: Albania" ],
[ '🇦🇲', [ 'Flag' ], "Flag: Armenia" ],
[ '🇦🇴', [ 'Flag' ], "Flag: Angola" ],
[ '🇦🇶', [ 'Flag' ], "Flag: Antarctica" ],
[ '🇦🇷', [ 'Flag' ], "Flag: Argentina" ],
[ '🇦🇸', [ 'Flag' ], "Flag: American Samoa" ],
[ '🇦🇹', [ 'Flag' ], "Flag: Austria" ],
[ '🇦🇺', [ 'Flag' ], "Flag: Australia" ],
[ '🇦🇼', [ 'Flag' ], "Flag: Aruba" ],
[ '🇦🇽', [ 'Flag' ], "Flag: Åland Islands" ],
[ '🇦🇿', [ 'Flag' ], "Flag: Azerbaijan" ],
[ '🇧🇦', [ 'Flag' ], "Flag: Bosnia & Herzegovina" ],
[ '🇧🇧', [ 'Flag' ], "Flag: Barbados" ],
[ '🇧🇩', [ 'Flag' ], "Flag: Bangladesh" ],
[ '🇧🇪', [ 'Flag' ], "Flag: Belgium" ],
[ '🇧🇫', [ 'Flag' ], "Flag: Burkina Faso" ],
[ '🇧🇬', [ 'Flag' ], "Flag: Bulgaria" ],
[ '🇧🇭', [ 'Flag' ], "Flag: Bahrain" ],
[ '🇧🇮', [ 'Flag' ], "Flag: Burundi" ],
[ '🇧🇯', [ 'Flag' ], "Flag: Benin" ],
[ '🇧🇱', [ 'Flag' ], "Flag: St. Barthélemy" ],
[ '🇧🇲', [ 'Flag' ], "Flag: Bermuda" ],
[ '🇧🇳', [ 'Flag' ], "Flag: Brunei" ],
[ '🇧🇴', [ 'Flag' ], "Flag: Bolivia" ],
[ '🇧🇶', [ 'Flag' ], "Flag: Caribbean Netherlands" ],
[ '🇧🇷', [ 'Flag' ], "Flag: Brazil" ],
[ '🇧🇸', [ 'Flag' ], "Flag: Bahamas" ],
[ '🇧🇹', [ 'Flag' ], "Flag: Bhutan" ],
[ '🇧🇻', [ 'Flag' ], "Flag: Bouvet Island" ],
[ '🇧🇼', [ 'Flag' ], "Flag: Botswana" ],
[ '🇧🇾', [ 'Flag' ], "Flag: Belarus" ],
[ '🇧🇿', [ 'Flag' ], "Flag: Belize" ],
[ '🇨🇦', [ 'Flag' ], "Flag: Canada" ],
[ '🇨🇨', [ 'Flag' ], "Flag: Cocos (Keeling) Islands" ],
[ '🇨🇩', [ 'Flag' ], "Flag: Congo - Kinshasa" ],
[ '🇨🇫', [ 'Flag' ], "Flag: Central African Republic" ],
[ '🇨🇬', [ 'Flag' ], "Flag: Congo - Brazzaville" ],
[ '🇨🇭', [ 'Flag' ], "Flag: Switzerland" ],
[ '🇨🇮', [ 'Flag' ], "Flag: Côte d’Ivoire" ],
[ '🇨🇰', [ 'Flag' ], "Flag: Cook Islands" ],
[ '🇨🇱', [ 'Flag' ], "Flag: Chile" ],
[ '🇨🇲', [ 'Flag' ], "Flag: Cameroon" ],
[ '🇨🇳', [ 'Flag' ], "Flag: China" ],
[ '🇨🇴', [ 'Flag' ], "Flag: Colombia" ],
[ '🇨🇵', [ 'Flag' ], "Flag: Clipperton Island" ],
[ '🇨🇷', [ 'Flag' ], "Flag: Costa Rica" ],
[ '🇨🇺', [ 'Flag' ], "Flag: Cuba" ],
[ '🇨🇻', [ 'Flag' ], "Flag: Cape Verde" ],
[ '🇨🇼', [ 'Flag' ], "Flag: Curaçao" ],
[ '🇨🇽', [ 'Flag' ], "Flag: Christmas Island" ],
[ '🇨🇾', [ 'Flag' ], "Flag: Cyprus" ],
[ '🇨🇿', [ 'Flag' ], "Flag: Czechia" ],
[ '🇩🇪', [ 'Flag' ], "Flag: Germany" ],
[ '🇩🇬', [ 'Flag' ], "Flag: Diego Garcia" ],
[ '🇩🇯', [ 'Flag' ], "Flag: Djibouti" ],
[ '🇩🇰', [ 'Flag' ], "Flag: Denmark" ],
[ '🇩🇲', [ 'Flag' ], "Flag: Dominica" ],
[ '🇩🇴', [ 'Flag' ], "Flag: Dominican Republic" ],
[ '🇩🇿', [ 'Flag' ], "Flag: Algeria" ],
[ '🇪🇦', [ 'Flag' ], "Flag: Ceuta & Melilla" ],
[ '🇪🇨', [ 'Flag' ], "Flag: Ecuador" ],
[ '🇪🇪', [ 'Flag' ], "Flag: Estonia" ],
[ '🇪🇬', [ 'Flag' ], "Flag: Egypt" ],
[ '🇪🇭', [ 'Flag' ], "Flag: Western Sahara" ],
[ '🇪🇷', [ 'Flag' ], "Flag: Eritrea" ],
[ '🇪🇸', [ 'Flag' ], "Flag: Spain" ],
[ '🇪🇹', [ 'Flag' ], "Flag: Ethiopia" ],
[ '🇪🇺', [ 'Flag' ], "Flag: European Union" ],
[ '🇫🇮', [ 'Flag' ], "Flag: Finland" ],
[ '🇫🇯', [ 'Flag' ], "Flag: Fiji" ],
[ '🇫🇰', [ 'Flag' ], "Flag: Falkland Islands" ],
[ '🇫🇲', [ 'Flag' ], "Flag: Micronesia" ],
[ '🇫🇴', [ 'Flag' ], "Flag: Faroe Islands" ],
[ '🇫🇷', [ 'Flag' ], "Flag: France" ],
[ '🇬🇦', [ 'Flag' ], "Flag: Gabon" ],
[ '🇬🇧', [ 'Flag' ], "Flag: United Kingdom" ],
[ '🇬🇩', [ 'Flag' ], "Flag: Grenada" ],
[ '🇬🇪', [ 'Flag' ], "Flag: Georgia" ],
[ '🇬🇫', [ 'Flag' ], "Flag: French Guiana" ],
[ '🇬🇬', [ 'Flag' ], "Flag: Guernsey" ],
[ '🇬🇭', [ 'Flag' ], "Flag: Ghana" ],
[ '🇬🇮', [ 'Flag' ], "Flag: Gibraltar" ],
[ '🇬🇱', [ 'Flag' ], "Flag: Greenland" ],
[ '🇬🇲', [ 'Flag' ], "Flag: Gambia" ],
[ '🇬🇳', [ 'Flag' ], "Flag: Guinea" ],
[ '🇬🇵', [ 'Flag' ], "Flag: Guadeloupe" ],
[ '🇬🇶', [ 'Flag' ], "Flag: Equatorial Guinea" ],
[ '🇬🇷', [ 'Flag' ], "Flag: Greece" ],
[ '🇬🇸', [ 'Flag' ], "Flag: South Georgia & South Sandwich Islands" ],
[ '🇬🇹', [ 'Flag' ], "Flag: Guatemala" ],
[ '🇬🇺', [ 'Flag' ], "Flag: Guam" ],
[ '🇬🇼', [ 'Flag' ], "Flag: Guinea-Bissau" ],
[ '🇬🇾', [ 'Flag' ], "Flag: Guyana" ],
[ '🇭🇰', [ 'Flag' ], "Flag: Hong Kong SAR China" ],
[ '🇭🇲', [ 'Flag' ], "Flag: Heard & McDonald Islands" ],
[ '🇭🇳', [ 'Flag' ], "Flag: Honduras" ],
[ '🇭🇷', [ 'Flag' ], "Flag: Croatia" ],
[ '🇭🇹', [ 'Flag' ], "Flag: Haiti" ],
[ '🇭🇺', [ 'Flag' ], "Flag: Hungary" ],
[ '🇮🇨', [ 'Flag' ], "Flag: Canary Islands" ],
[ '🇮🇩', [ 'Flag' ], "Flag: Indonesia" ],
[ '🇮🇪', [ 'Flag' ], "Flag: Ireland" ],
[ '🇮🇱', [ 'Flag' ], "Flag: Israel" ],
[ '🇮🇲', [ 'Flag' ], "Flag: Isle of Man" ],
[ '🇮🇳', [ 'Flag' ], "Flag: India" ],
[ '🇮🇴', [ 'Flag' ], "Flag: British Indian Ocean Territory" ],
[ '🇮🇶', [ 'Flag' ], "Flag: Iraq" ],
[ '🇮🇷', [ 'Flag' ], "Flag: Iran" ],
[ '🇮🇸', [ 'Flag' ], "Flag: Iceland" ],
[ '🇮🇹', [ 'Flag' ], "Flag: Italy" ],
[ '🇯🇪', [ 'Flag' ], "Flag: Jersey" ],
[ '🇯🇲', [ 'Flag' ], "Flag: Jamaica" ],
[ '🇯🇴', [ 'Flag' ], "Flag: Jordan" ],
[ '🇯🇵', [ 'Flag' ], "Flag: Japan" ],
[ '🇰🇪', [ 'Flag' ], "Flag: Kenya" ],
[ '🇰🇬', [ 'Flag' ], "Flag: Kyrgyzstan" ],
[ '🇰🇭', [ 'Flag' ], "Flag: Cambodia" ],
[ '🇰🇮', [ 'Flag' ], "Flag: Kiribati" ],
[ '🇰🇲', [ 'Flag' ], "Flag: Comoros" ],
[ '🇰🇳', [ 'Flag' ], "Flag: St. Kitts & Nevis" ],
[ '🇰🇵', [ 'Flag' ], "Flag: North Korea" ],
[ '🇰🇷', [ 'Flag' ], "Flag: South Korea" ],
[ '🇰🇼', [ 'Flag' ], "Flag: Kuwait" ],
[ '🇰🇾', [ 'Flag' ], "Flag: Cayman Islands" ],
[ '🇰🇿', [ 'Flag' ], "Flag: Kazakhstan" ],
[ '🇱🇦', [ 'Flag' ], "Flag: Laos" ],
[ '🇱🇧', [ 'Flag' ], "Flag: Lebanon" ],
[ '🇱🇨', [ 'Flag' ], "Flag: St. Lucia" ],
[ '🇱🇮', [ 'Flag' ], "Flag: Liechtenstein" ],
[ '🇱🇰', [ 'Flag' ], "Flag: Sri Lanka" ],
[ '🇱🇷', [ 'Flag' ], "Flag: Liberia" ],
[ '🇱🇸', [ 'Flag' ], "Flag: Lesotho" ],
[ '🇱🇹', [ 'Flag' ], "Flag: Lithuania" ],
[ '🇱🇺', [ 'Flag' ], "Flag: Luxembourg" ],
[ '🇱🇻', [ 'Flag' ], "Flag: Latvia" ],
[ '🇱🇾', [ 'Flag' ], "Flag: Libya" ],
[ '🇲🇦', [ 'Flag' ], "Flag: Morocco" ],
[ '🇲🇨', [ 'Flag' ], "Flag: Monaco" ],
[ '🇲🇩', [ 'Flag' ], "Flag: Moldova" ],
[ '🇲🇪', [ 'Flag' ], "Flag: Montenegro" ],
[ '🇲🇫', [ 'Flag' ], "Flag: St. Martin" ],
[ '🇲🇬', [ 'Flag' ], "Flag: Madagascar" ],
[ '🇲🇭', [ 'Flag' ], "Flag: Marshall Islands" ],
[ '🇲🇰', [ 'Flag' ], "Flag: North Macedonia" ],
[ '🇲🇱', [ 'Flag' ], "Flag: Mali" ],
[ '🇲🇲', [ 'Flag' ], "Flag: Myanmar (Burma)" ],
[ '🇲🇳', [ 'Flag' ], "Flag: Mongolia" ],
[ '🇲🇴', [ 'Flag' ], "Flag: Macao Sar China" ],
[ '🇲🇵', [ 'Flag' ], "Flag: Northern Mariana Islands" ],
[ '🇲🇶', [ 'Flag' ], "Flag: Martinique" ],
[ '🇲🇷', [ 'Flag' ], "Flag: Mauritania" ],
[ '🇲🇸', [ 'Flag' ], "Flag: Montserrat" ],
[ '🇲🇹', [ 'Flag' ], "Flag: Malta" ],
[ '🇲🇺', [ 'Flag' ], "Flag: Mauritius" ],
[ '🇲🇻', [ 'Flag' ], "Flag: Maldives" ],
[ '🇲🇼', [ 'Flag' ], "Flag: Malawi" ],
[ '🇲🇽', [ 'Flag' ], "Flag: Mexico" ],
[ '🇲🇾', [ 'Flag' ], "Flag: Malaysia" ],
[ '🇲🇿', [ 'Flag' ], "Flag: Mozambique" ],
[ '🇳🇦', [ 'Flag' ], "Flag: Namibia" ],
[ '🇳🇨', [ 'Flag' ], "Flag: New Caledonia" ],
[ '🇳🇪', [ 'Flag' ], "Flag: Niger" ],
[ '🇳🇫', [ 'Flag' ], "Flag: Norfolk Island" ],
[ '🇳🇬', [ 'Flag' ], "Flag: Nigeria" ],
[ '🇳🇮', [ 'Flag' ], "Flag: Nicaragua" ],
[ '🇳🇱', [ 'Flag' ], "Flag: Netherlands" ],
[ '🇳🇴', [ 'Flag' ], "Flag: Norway" ],
[ '🇳🇵', [ 'Flag' ], "Flag: Nepal" ],
[ '🇳🇷', [ 'Flag' ], "Flag: Nauru" ],
[ '🇳🇺', [ 'Flag' ], "Flag: Niue" ],
[ '🇳🇿', [ 'Flag' ], "Flag: New Zealand" ],
[ '🇴🇲', [ 'Flag' ], "Flag: Oman" ],
[ '🇵🇦', [ 'Flag' ], "Flag: Panama" ],
[ '🇵🇪', [ 'Flag' ], "Flag: Peru" ],
[ '🇵🇫', [ 'Flag' ], "Flag: French Polynesia" ],
[ '🇵🇬', [ 'Flag' ], "Flag: Papua New Guinea" ],
[ '🇵🇭', [ 'Flag' ], "Flag: Philippines" ],
[ '🇵🇰', [ 'Flag' ], "Flag: Pakistan" ],
[ '🇵🇱', [ 'Flag' ], "Flag: Poland" ],
[ '🇵🇲', [ 'Flag' ], "Flag: St. Pierre & Miquelon" ],
[ '🇵🇳', [ 'Flag' ], "Flag: Pitcairn Islands" ],
[ '🇵🇷', [ 'Flag' ], "Flag: Puerto Rico" ],
[ '🇵🇸', [ 'Flag' ], "Flag: Palestinian Territories" ],
[ '🇵🇹', [ 'Flag' ], "Flag: Portugal" ],
[ '🇵🇼', [ 'Flag' ], "Flag: Palau" ],
[ '🇵🇾', [ 'Flag' ], "Flag: Paraguay" ],
[ '🇶🇦', [ 'Flag' ], "Flag: Qatar" ],
[ '🇷🇪', [ 'Flag' ], "Flag: Réunion" ],
[ '🇷🇴', [ 'Flag' ], "Flag: Romania" ],
[ '🇷🇸', [ 'Flag' ], "Flag: Serbia" ],
[ '🇷🇺', [ 'Flag' ], "Flag: Russia" ],
[ '🇷🇼', [ 'Flag' ], "Flag: Rwanda" ],
[ '🇸🇦', [ 'Flag' ], "Flag: Saudi Arabia" ],
[ '🇸🇧', [ 'Flag' ], "Flag: Solomon Islands" ],
[ '🇸🇨', [ 'Flag' ], "Flag: Seychelles" ],
[ '🇸🇩', [ 'Flag' ], "Flag: Sudan" ],
[ '🇸🇪', [ 'Flag' ], "Flag: Sweden" ],
[ '🇸🇬', [ 'Flag' ], "Flag: Singapore" ],
[ '🇸🇭', [ 'Flag' ], "Flag: St. Helena" ],
[ '🇸🇮', [ 'Flag' ], "Flag: Slovenia" ],
[ '🇸🇯', [ 'Flag' ], "Flag: Svalbard & Jan Mayen" ],
[ '🇸🇰', [ 'Flag' ], "Flag: Slovakia" ],
[ '🇸🇱', [ 'Flag' ], "Flag: Sierra Leone" ],
[ '🇸🇲', [ 'Flag' ], "Flag: San Marino" ],
[ '🇸🇳', [ 'Flag' ], "Flag: Senegal" ],
[ '🇸🇴', [ 'Flag' ], "Flag: Somalia" ],
[ '🇸🇷', [ 'Flag' ], "Flag: Suriname" ],
[ '🇸🇸', [ 'Flag' ], "Flag: South Sudan" ],
[ '🇸🇹', [ 'Flag' ], "Flag: São Tomé & Príncipe" ],
[ '🇸🇻', [ 'Flag' ], "Flag: El Salvador" ],
[ '🇸🇽', [ 'Flag' ], "Flag: Sint Maarten" ],
[ '🇸🇾', [ 'Flag' ], "Flag: Syria" ],
[ '🇸🇿', [ 'Flag' ], "Flag: Eswatini" ],
[ '🇹🇦', [ 'Flag' ], "Flag: Tristan Da Cunha" ],
[ '🇹🇨', [ 'Flag' ], "Flag: Turks & Caicos Islands" ],
[ '🇹🇩', [ 'Flag' ], "Flag: Chad" ],
[ '🇹🇫', [ 'Flag' ], "Flag: French Southern Territories" ],
[ '🇹🇬', [ 'Flag' ], "Flag: Togo" ],
[ '🇹🇭', [ 'Flag' ], "Flag: Thailand" ],
[ '🇹🇯', [ 'Flag' ], "Flag: Tajikistan" ],
[ '🇹🇰', [ 'Flag' ], "Flag: Tokelau" ],
[ '🇹🇱', [ 'Flag' ], "Flag: Timor-Leste" ],
[ '🇹🇲', [ 'Flag' ], "Flag: Turkmenistan" ],
[ '🇹🇳', [ 'Flag' ], "Flag: Tunisia" ],
[ '🇹🇴', [ 'Flag' ], "Flag: Tonga" ],
[ '🇹🇷', [ 'Flag' ], "Flag: Turkey" ],
[ '🇹🇹', [ 'Flag' ], "Flag: Trinidad & Tobago" ],
[ '🇹🇻', [ 'Flag' ], "Flag: Tuvalu" ],
[ '🇹🇼', [ 'Flag' ], "Flag: Taiwan" ],
[ '🇹🇿', [ 'Flag' ], "Flag: Tanzania" ],
[ '🇺🇦', [ 'Flag' ], "Flag: Ukraine" ],
[ '🇺🇬', [ 'Flag' ], "Flag: Uganda" ],
[ '🇺🇲', [ 'Flag' ], "Flag: U.S. Outlying Islands" ],
[ '🇺🇳', [ 'Flag' ], "Flag: United Nations" ],
[ '🇺🇸', [ 'Flag' ], "Flag: United States" ],
[ '🇺🇾', [ 'Flag' ], "Flag: Uruguay" ],
[ '🇺🇿', [ 'Flag' ], "Flag: Uzbekistan" ],
[ '🇻🇦', [ 'Flag' ], "Flag: Vatican City" ],
[ '🇻🇨', [ 'Flag' ], "Flag: St. Vincent & Grenadines" ],
[ '🇻🇪', [ 'Flag' ], "Flag: Venezuela" ],
[ '🇻🇬', [ 'Flag' ], "Flag: British Virgin Islands" ],
[ '🇻🇮', [ 'Flag' ], "Flag: U.S. Virgin Islands" ],
[ '🇻🇳', [ 'Flag' ], "Flag: Vietnam" ],
[ '🇻🇺', [ 'Flag' ], "Flag: Vanuatu" ],
[ '🇼🇫', [ 'Flag' ], "Flag: Wallis & Futuna" ],
[ '🇼🇸', [ 'Flag' ], "Flag: Samoa" ],
[ '🇽🇰', [ 'Flag' ], "Flag: Kosovo" ],
[ '🇾🇪', [ 'Flag' ], "Flag: Yemen" ],
[ '🇾🇹', [ 'Flag' ], "Flag: Mayotte" ],
[ '🇿🇦', [ 'Flag' ], "Flag: South Africa" ],
[ '🇿🇲', [ 'Flag' ], "Flag: Zambia" ],
[ '🇿🇼', [ 'Flag' ], "Flag: Zimbabwe" ],
[ '🚣', [ 'Travel' ], "Person Rowing Boat" ],
[ '🗾', [ 'Travel' ], "Map of Japan" ],
[ '🏔️', [ 'Object', 'Travel' ], "Snow-Capped Mountain" ],
[ '🌋', [ 'Object', 'Travel' ], "Volcano" ],
[ '🏕️', [ 'Travel' ], "Camping" ],
[ '🏖️', [ 'Travel' ], "Beach with Umbrella" ],
[ '🏜️', [ 'Travel' ], "Desert" ],
[ '🏝️', [ 'Travel' ], "Desert Island" ],
[ '🏞️', [ 'Travel' ], "National Park" ],
[ '🏟️', [ 'Travel' ], "Stadium" ],
[ '🏛️', [ 'Travel' ], "Classical Building" ],
[ '🏗️', [ 'Travel' ], "Building Construction" ],
[ '🏚️', [ 'Travel' ], "Derelict House" ],
[ '🏡', [ 'Travel' ], "House with Garden" ],
[ '🏢', [ 'Travel' ], "Office Building" ],
[ '🏥', [ 'Travel' ], "Hospital" ],
[ '🏨', [ 'Travel' ], "Hotel" ],
[ '🏪', [ 'Travel' ], "Convenience Store" ],
[ '🏫', [ 'Object', 'Travel' ], "School" ],
[ '🏭', [ 'Object', 'Travel' ], "Factory" ],
[ '🏰', [ 'Object', 'Travel' ], "Castle" ],
[ '🗽', [ 'Object', 'Travel' ], "Statue of Liberty" ],
[ '⛪', [ 'Travel' ], "Church" ],
[ '🕌', [ 'Travel' ], "Mosque" ],
[ '🛕', [ 'Travel' ], "Hindu Temple" ],
[ '🕍', [ 'Travel' ], "Synagogue" ],
[ '⛩️', [ 'Travel' ], "Shinto Shrine" ],
[ '🕋', [ 'Travel' ], "Kaaba" ],
[ '⛲', [ 'Object', 'Travel' ], "Fountain" ],
[ '⛺', [ 'Travel' ], "Tent" ],
[ '🌃', [ 'Travel' ], "Night with Stars" ],
[ '🏙️', [ 'Travel' ], "Cityscape" ],
[ '🌄', [ 'Travel' ], "Sunrise Over Mountains" ],
[ '🌅', [ 'Travel' ], "Sunrise" ],
[ '🌇', [ 'Travel' ], "Sunset" ],
[ '🌉', [ 'Travel' ], "Bridge at Night" ],
[ '🎠', [ 'Object', 'Travel' ], "Carousel Horse" ],
[ '🎡', [ 'Object', 'Travel' ], "Ferris Wheel" ],
[ '🎢', [ 'Object', 'Travel' ], "Roller Coaster" ],
[ '🚂', [ 'Object', 'Travel' ], "Locomotive" ],
[ '🚇', [ 'Travel' ], "Metro" ],
[ '🚌', [ 'Object', 'Travel' ], "Bus" ],
[ '🚑', [ 'Object', 'Travel' ], "Ambulance" ],
[ '🚒', [ 'Object', 'Travel' ], "Fire Engine" ],
[ '🚓', [ 'Object', 'Travel' ], "Police Car" ],
[ '🚕', [ 'Object', 'Travel' ], "Taxi" ],
[ '🚗', [ 'Object', 'Travel' ], "Automobile" ],
[ '🚚', [ 'Object', 'Travel' ], "Delivery Truck" ],
[ '🚜', [ 'Object', 'Travel' ], "Tractor" ],
[ '🏎️', [ 'Object', 'Travel' ], "Racing Car" ],
[ '🏍️', [ 'Object', 'Travel' ], "Motorcycle" ],
[ '🛵', [ 'Travel' ], "Motor Scooter" ],
[ '🛺', [ 'Travel' ], "Auto Rickshaw" ],
[ '🚲', [ 'Object', 'Travel' ], "Bicycle" ],
[ '🛴', [ 'Object', 'Travel' ], "Kick Scooter" ],
[ '⛽', [ 'Travel' ], "Fuel Pump" ],
[ '🚦', [ 'Object', 'Object' , 'Travel'], "Vertical Traffic Light" ],
[ '🚧', [ 'Travel' ], "Construction" ],
[ '⚓', [ 'Object', 'Travel' ], "Anchor" ],
[ '⛵', [ 'Object', 'Travel' ], "Sailboat" ],
[ '🚤', [ 'Travel' ], "Speedboat" ],
[ '🛳️', [ 'Travel' ], "Passenger Ship" ],
[ '✈️', [ 'Object', 'Travel' ], "Airplane" ],
[ '🛩️', [ 'Travel' ], "Small Airplane" ],
[ '🪂', [ 'Travel' ], "Parachute" ],
[ '🚁', [ 'Object', 'Travel' ], "Helicopter" ],
[ '🚟', [ 'Travel' ], "Suspension Railway" ],
[ '🛰️', [ 'Object' ], "Satellite" ],
[ '🚀', [ 'Object', 'Travel' ], "Rocket" ],
[ '🛸', [ 'Object' ], "Flying Saucer" ],
[ '🪐', [ 'Object' ], "Ringed Planet" ],
[ '🌠', [ 'Object' ], "Shooting Star" ],
[ '🌌', [ ], "Milky Way" ],
[ '🎆', [ 'Object' ], "Fireworks" ],
[ '🎇', [ ], "Sparkler" ],
[ '💷', [ 'Object', 'Travel' ], "Pound Banknote" ],
[ '🗿', [ 'Object' , 'Travel'], "Moai" ],
[ '❤️', [ 'Object' ], "Red Heart" ],
[ '💬', [ ], "Speech Balloon" ],
[ '💤', [ ], "ZZZ" ],
[ '💈', [ 'Object' ], "Barber Pole" ],
[ '🛑', [ 'Object' ], "Stop Sign" ],
[ '🕒', [ 'Object' ], "Clock" ],
[ '🃏', [ 'Object' ], "Joker" ],
[ '📣', [ 'Object' ], "Megaphone" ],
[ '🔔', [ 'Object' ], "Bell" ],
[ '💲', [ ], "Dollar Sign" ],
[ '💥', [ ], "Collision" ],
[ '🐒', [ 'Animal & Nature', 'Animal' ], "Monkey" ],
[ '🦍', [ 'Animal & Nature', 'Animal' ], "Gorilla" ],
[ '🦧', [ 'Animal & Nature', 'Animal' ], "Orangutan" ],
[ '🐶', [ 'Object', 'Animal & Nature', 'Animal' ], "Dog Face" ],
[ '🐩', [ 'Animal & Nature', 'Animal' ], "Poodle" ],
[ '🐺', [ 'Animal & Nature', 'Animal' ], "Wolf" ],
[ '🦊', [ 'Animal & Nature', 'Animal' ], "Fox" ],
[ '🦝', [ 'Animal & Nature', 'Animal' ], "Raccoon" ],
[ '🐱', [ 'Object', 'Animal & Nature', 'Animal' ], "Cat Face" ],
[ '🦁', [ 'Animal & Nature', 'Animal' ], "Lion" ],
[ '🐅', [ 'Animal & Nature', 'Animal' ], "Tiger" ],
[ '🐆', [ 'Animal & Nature', 'Animal' ], "Leopard" ],
[ '🐎', [ 'Animal & Nature', 'Animal' ], "Horse" ],
[ '🦄', [ 'Animal & Nature', 'Animal' ], "Unicorn" ],
[ '🦓', [ 'Animal & Nature', 'Animal' ], "Zebra" ],
[ '🦌', [ 'Animal & Nature', 'Animal' ], "Deer" ],
[ '🐂', [ 'Animal & Nature', 'Animal' ], "Ox" ],
[ '🐃', [ 'Animal & Nature', 'Animal' ], "Water Buffalo" ],
[ '🐄', [ 'Animal & Nature', 'Animal' ], "Cow" ],
[ '🐷', [ 'Animal & Nature', 'Animal' ], "Pig Face" ],
[ '🐗', [ 'Animal & Nature', 'Animal' ], "Boar" ],
[ '🐏', [ 'Animal & Nature', 'Animal' ], "Ram" ],
[ '🐑', [ 'Animal & Nature', 'Animal' ], "Ewe" ],
[ '🐐', [ 'Animal & Nature', 'Animal' ], "Goat" ],
[ '🐫', [ 'Animal & Nature', 'Animal' ], "Two-Hump Camel" ],
[ '🦙', [ 'Animal & Nature', 'Animal' ], "Llama" ],
[ '🦒', [ 'Animal & Nature', 'Animal' ], "Giraffe" ],
[ '🐘', [ 'Animal & Nature', 'Animal' ], "Elephant" ],
[ '🦏', [ 'Animal & Nature', 'Animal' ], "Rhinoceros" ],
[ '🦛', [ 'Animal & Nature', 'Animal' ], "Hippopotamus" ],
[ '🐭', [ 'Animal & Nature', 'Animal' ], "Mouse Face" ],
[ '🐀', [ 'Animal & Nature', 'Animal' ], "Rat" ],
[ '🐹', [ 'Animal & Nature', 'Animal' ], "Hamster" ],
[ '🐰', [ 'Animal & Nature', 'Animal' ], "Rabbit Face" ],
[ '🐿️', [ 'Animal & Nature', 'Animal' ], "Chipmunk" ],
[ '🦔', [ 'Animal & Nature', 'Animal' ], "Hedgehog" ],
[ '🦇', [ 'Animal & Nature', 'Animal' ], "Bat" ],
[ '🐻', [ 'Animal & Nature', 'Animal' ], "Bear" ],
[ '🐨', [ 'Animal & Nature', 'Animal' ], "Koala" ],
[ '🐼', [ 'Animal & Nature', 'Animal' ], "Panda" ],
[ '🦥', [ 'Animal & Nature', 'Animal' ], "Sloth" ],
[ '🦦', [ 'Animal & Nature', 'Animal' ], "Otter" ],
[ '🦨', [ 'Animal & Nature', 'Animal' ], "Skunk" ],
[ '🦘', [ 'Animal & Nature', 'Animal' ], "Kangaroo" ],
[ '🦡', [ 'Animal & Nature', 'Animal' ], "Badger" ],
[ '🐾', [ 'Animal & Nature' ], "Paw Prints" ],
[ '🦃', [ 'Animal & Nature', 'Animal' ], "Turkey" ],
[ '🐔', [ 'Animal & Nature', 'Animal' ], "Chicken" ],
[ '🐓', [ 'Animal & Nature', 'Animal' ], "Rooster" ],
[ '🐣', [ 'Animal & Nature', 'Animal' ], "Hatching Chick" ],
[ '🐦', [ 'Object', 'Animal & Nature', 'Animal' ], "Bird" ],
[ '🐧', [ 'Animal & Nature', 'Animal' ], "Penguin" ],
[ '🕊️', [ 'Animal & Nature', 'Animal' ], "Dove" ],
[ '🦅', [ 'Animal & Nature', 'Animal' ], "Eagle" ],
[ '🦆', [ 'Animal & Nature', 'Animal' ], "Duck" ],
[ '🦢', [ 'Animal & Nature', 'Animal' ], "Swan" ],
[ '🦉', [ 'Animal & Nature', 'Animal' ], "Owl" ],
[ '🦩', [ 'Animal & Nature', 'Animal' ], "Flamingo" ],
[ '🦚', [ 'Animal & Nature', 'Animal' ], "Peacock" ],
[ '🦜', [ 'Animal & Nature', 'Animal' ], "Parrot" ],
[ '🐸', [ 'Animal & Nature', 'Animal' ], "Frog" ],
[ '🐊', [ 'Animal & Nature', 'Animal' ], "Crocodile" ],
[ '🐢', [ 'Animal & Nature', 'Animal' ], "Turtle" ],
[ '🦎', [ 'Animal & Nature', 'Animal' ], "Lizard" ],
[ '🐍', [ 'Animal & Nature', 'Animal' ], "Snake" ],
[ '🐲', [ 'Animal & Nature', 'Animal' ], "Dragon Face" ],
[ '🐉', [ 'Animal & Nature', 'Animal' ], "Dragon" ],
[ '🦕', [ 'Animal & Nature', 'Animal' ], "Sauropod" ],
[ '🦖', [ 'Animal & Nature', 'Animal' ], "T-Rex" ],
[ '🐳', [ 'Animal & Nature', 'Animal' ], "Spouting Whale" ],
[ '🐬', [ 'Animal & Nature', 'Animal' ], "Dolphin" ],
[ '🐟', [ 'Object', 'Animal & Nature', 'Animal' ], "Fish" ],
[ '🐠', [ 'Animal & Nature', 'Animal' ], "Tropical Fish" ],
[ '🐡', [ 'Animal & Nature', 'Animal' ], "Blowfish" ],
[ '🦈', [ 'Animal & Nature', 'Animal' ], "Shark" ],
[ '🐙', [ 'Animal & Nature', 'Animal' ], "Octopus" ],
[ '🐚', [ 'Animal & Nature', 'Animal' ], "Spiral Shell" ],
[ '🐌', [ 'Animal & Nature', 'Animal' ], "Snail" ],
[ '🦋', [ 'Animal & Nature', 'Animal' ], "Butterfly" ],
[ '🐛', [ 'Animal & Nature', 'Animal' ], "Bug" ],
[ '🐜', [ 'Animal & Nature', 'Animal' ], "Ant" ],
[ '🐝', [ 'Animal & Nature', 'Animal' ], "Honeybee" ],
[ '🐞', [ 'Animal & Nature', 'Animal' ], "Lady Beetle" ],
[ '🦗', [ 'Animal & Nature', 'Animal' ], "Cricket" ],
[ '🕷️', [ 'Animal & Nature', 'Animal' ], "Spider" ],
[ '🕸️', [ 'Object', 'Animal & Nature' ], "Spider Web" ],
[ '🦂', [ 'Animal & Nature', 'Animal' ], "Scorpion" ],
[ '🦟', [ 'Animal & Nature', 'Animal' ], "Mosquito" ],
[ '🦠', [ 'Animal & Nature', 'Animal' ], "Microbe" ],
[ '💐', [ 'Animal & Nature', 'Nature' ], "Bouquet" ],
[ '🌸', [ 'Animal & Nature', 'Nature' ], "Cherry Blossom" ],
[ '💮', [ 'Animal & Nature', 'Nature' ], "White Flower" ],
[ '🏵️', [ 'Animal & Nature', 'Nature' ], "Rosette" ],
[ '🌹', [ 'Object', 'Animal & Nature', 'Nature' ], "Rose" ],
[ '🥀', [ 'Animal & Nature', 'Nature' ], "Wilted Flower" ],
[ '🌺', [ 'Animal & Nature', 'Nature' ], "Hibiscus" ],
[ '🌻', [ 'Animal & Nature', 'Nature' ], "Sunflower" ],
[ '🌼', [ 'Object', 'Animal & Nature', 'Nature' ], "Blossom" ],
[ '🌷', [ 'Animal & Nature', 'Nature' ], "Tulip" ],
[ '🌱', [ 'Object', 'Animal & Nature', 'Nature' ], "Seedling" ],
[ '🌲', [ 'Object', 'Animal & Nature', 'Nature' ], "Evergreen Tree" ],
[ '🌳', [ 'Animal & Nature', 'Nature' ], "Deciduous Tree" ],
[ '🌴', [ 'Animal & Nature', 'Nature' ], "Palm Tree" ],
[ '🌵', [ 'Object', 'Animal & Nature', 'Nature' ], "Cactus" ],
[ '🌾', [ 'Animal & Nature', 'Nature' ], "Sheaf of Rice" ],
[ '🌿', [ 'Animal & Nature', 'Nature' ], "Herb" ],
[ '☘️', [ 'Animal & Nature', 'Nature' ], "Shamrock" ],
[ '🍀', [ 'Animal & Nature', 'Nature' ], "Four Leaf Clover" ],
[ '🍁', [ 'Animal & Nature', 'Nature' ], "Maple Leaf" ],
[ '🍂', [ 'Object', 'Animal & Nature', 'Nature' ], "Fallen Leaf" ],
[ '🍃', [ 'Animal & Nature', 'Nature' ], "Leaf Fluttering in Wind" ],
[ '🍄', [ 'Object', 'Animal & Nature', 'Nature' ], "Mushroom" ],
[ '🌰', [ 'Animal & Nature', 'Nature' ], "Chestnut" ],
[ '🦀', [ 'Animal & Nature', 'Animal' ], "Crab" ],
[ '🦞', [ 'Animal & Nature', 'Animal' ], "Lobster" ],
[ '🦐', [ 'Animal & Nature', 'Animal' ], "Shrimp" ],
[ '🦑', [ 'Animal & Nature', 'Animal' ], "Squid" ],
[ '🌍', [ 'Travel', 'Object', 'Animal & Nature' ], "Globe Showing Europe-Africa" ],
[ '🌙', [ 'Object', 'Animal & Nature' ], "Crescent Moon" ],
[ '☀️', [ 'Object', 'Animal & Nature' ], "Sun" ],
[ '⭐', [ 'Object', 'Animal & Nature' ], "Star" ],
[ '🌠', [ 'Animal & Nature' ], "Shooting Star" ],
[ '☁️', [ 'Object', 'Animal & Nature' ], "Cloud" ],
[ '🌨️', [ 'Animal & Nature' ], "Cloud with Snow" ],
[ '🌩️', [ 'Animal & Nature' ], "Cloud with Lightning" ],
[ '🌪️', [ 'Animal & Nature' ], "Tornado" ],
[ '🌈', [ 'Object', 'Animal & Nature' ], "Rainbow" ],
[ '☔', [ 'Object', 'Animal & Nature' ], "Umbrella with Rain Drops" ],
[ '⚡', [ 'Animal & Nature' ], "High Voltage" ],
[ '❄️', [ 'Animal & Nature' ], "Snowflake" ],
[ '☃️', [ 'Object', 'Animal & Nature' ], "Snowman" ],
[ '☄️', [ 'Animal & Nature' ], "Comet" ],
[ '🔥', [ 'Object', 'Animal & Nature' ], "Fire" ],
[ '💧', [ 'Object', 'Animal & Nature' ], "Droplet" ],
[ '🌊', [ 'Animal & Nature' ], "Water Wave" ],
[ '🎄', [ 'Object', 'Animal & Nature' ], "Christmas Tree" ],
[ '✨', [ 'Animal & Nature' ], "Sparkles" ],
[ '😀', [ 'Emotion' ], "Grinning Face" ],
[ '😃', [ 'Emotion' ], "Grinning Face with Big Eyes" ],
[ '😄', [ 'Emotion' ], "Grinning Face with Smiling Eyes" ],
[ '😁', [ 'Emotion' ], "Beaming Face with Smiling Eyes" ],
[ '😆', [ 'Emotion' ], "Grinning Squinting Face" ],
[ '😅', [ 'Emotion' ], "Grinning Face with Sweat" ],
[ '🤣', [ 'Emotion' ], "Rolling on the Floor Laughing" ],
[ '😂', [ 'Emotion' ], "Face with Tears of Joy" ],
[ '🙂', [ 'Emotion' ], "Slightly Smiling Face" ],
[ '🙃', [ 'Emotion' ], "Upside-Down Face" ],
[ '😉', [ 'Emotion' ], "Winking Face" ],
[ '😊', [ 'Emotion' ], "Smiling Face with Smiling Eyes" ],
[ '😇', [ 'Emotion' ], "Smiling Face with Halo" ],
[ '🥰', [ 'Emotion' ], "Smiling Face with Hearts" ],
[ '😍', [ 'Emotion' ], "Smiling Face with Heart-Eyes" ],
[ '🤩', [ 'Emotion' ], "Star-Struck" ],
[ '😘', [ 'Emotion' ], "Face Blowing a Kiss" ],
[ '😗', [ 'Emotion' ], "Kissing Face" ],
//[ '☺️', [ 'Emotion' ], "Smiling Face" ],
[ '😚', [ 'Emotion' ], "Kissing Face with Closed Eyes" ],
[ '😙', [ 'Emotion' ], "Kissing Face with Smiling Eyes" ],
[ '😋', [ 'Emotion' ], "Face Savoring Food" ],
[ '😛', [ 'Emotion' ], "Face with Tongue" ],
[ '😜', [ 'Emotion' ], "Winking Face with Tongue" ],
[ '🤪', [ 'Emotion' ], "Zany Face" ],
[ '😝', [ 'Emotion' ], "Squinting Face with Tongue" ],
[ '🤑', [ 'Emotion' ], "Money-Mouth Face" ],
[ '🤗', [ 'Emotion' ], "Hugging Face" ],
[ '🤭', [ 'Emotion' ], "Face with Hand Over Mouth" ],
[ '🤫', [ 'Emotion' ], "Shushing Face" ],
[ '🤔', [ 'Emotion' ], "Thinking Face" ],
[ '🤐', [ 'Emotion' ], "Zipper-Mouth Face" ],
[ '🤨', [ 'Emotion' ], "Face with Raised Eyebrow" ],
[ '😐', [ 'Emotion' ], "Neutral Face" ],
[ '😑', [ 'Emotion' ], "Expressionless Face" ],
[ '😶', [ 'Emotion' ], "Face Without Mouth" ],
[ '😏', [ 'Emotion' ], "Smirking Face" ],
[ '😒', [ 'Emotion' ], "Unamused Face" ],
[ '🙄', [ 'Emotion' ], "Face with Rolling Eyes" ],
[ '😬', [ 'Emotion' ], "Grimacing Face" ],
[ '🤥', [ 'Emotion' ], "Lying Face" ],
[ '😌', [ 'Emotion' ], "Relieved Face" ],
[ '😔', [ 'Emotion' ], "Pensive Face" ],
[ '😪', [ 'Emotion' ], "Sleepy Face" ],
[ '🤤', [ 'Emotion' ], "Drooling Face" ],
[ '😴', [ 'Emotion' ], "Sleeping Face" ],
[ '😷', [ 'Emotion' ], "Face with Medical Mask" ],
[ '🤒', [ 'Emotion' ], "Face with Thermometer" ],
[ '🤕', [ 'Emotion' ], "Face with Head-Bandage" ],
[ '🤢', [ 'Emotion' ], "Nauseated Face" ],
[ '🤮', [ 'Emotion' ], "Face Vomiting" ],
[ '🤧', [ 'Emotion' ], "Sneezing Face" ],
[ '🥵', [ 'Emotion' ], "Hot Face" ],
[ '🥶', [ 'Emotion' ], "Cold Face" ],
[ '🥴', [ 'Emotion' ], "Woozy Face" ],
[ '😵', [ 'Emotion' ], "Dizzy Face" ],
[ '🤯', [ 'Emotion' ], "Exploding Head" ],
[ '🤠', [ 'Emotion' ], "Cowboy Hat Face" ],
[ '🥳', [ 'Emotion' ], "Partying Face" ],
[ '😎', [ 'Emotion' ], "Smiling Face with Sunglasses" ],
[ '🤓', [ 'Emotion' ], "Nerd Face" ],
[ '🧐', [ 'Emotion' ], "Face with Monocle" ],
[ '😕', [ 'Emotion' ], "Confused Face" ],
[ '😟', [ 'Emotion' ], "Worried Face" ],
[ '🙁', [ 'Emotion' ], "Slightly Frowning Face" ],
[ '☹️', [ 'Emotion' ], "Frowning Face" ],
[ '😮', [ 'Emotion' ], "Face with Open Mouth" ],
[ '😯', [ 'Emotion' ], "Hushed Face" ],
[ '😲', [ 'Emotion' ], "Astonished Face" ],
[ '😳', [ 'Emotion' ], "Flushed Face" ],
[ '🥺', [ 'Emotion' ], "Pleading Face" ],
[ '😦', [ 'Emotion' ], "Frowning Face with Open Mouth" ],
[ '😧', [ 'Emotion' ], "Anguished Face" ],
[ '😨', [ 'Emotion' ], "Fearful Face" ],
[ '😰', [ 'Emotion' ], "Anxious Face with Sweat" ],
[ '😥', [ 'Emotion' ], "Sad but Relieved Face" ],
[ '😢', [ 'Emotion' ], "Crying Face" ],
[ '😭', [ 'Emotion' ], "Loudly Crying Face" ],
[ '😱', [ 'Emotion' ], "Face Screaming in Fear" ],
[ '😖', [ 'Emotion' ], "Confounded Face" ],
[ '😣', [ 'Emotion' ], "Persevering Face" ],
[ '😞', [ 'Emotion' ], "Disappointed Face" ],
[ '😓', [ 'Emotion' ], "Downcast Face with Sweat" ],
[ '😩', [ 'Emotion' ], "Weary Face" ],
[ '😫', [ 'Emotion' ], "Tired Face" ],
[ '🥱', [ 'Emotion' ], "Yawning Face" ],
[ '😤', [ 'Emotion' ], "Face with Steam From Nose" ],
[ '😡', [ 'Emotion' ], "Pouting Face" ],
[ '😠', [ 'Emotion' ], "Angry Face" ],
[ '🤬', [ 'Emotion' ], "Face with Symbols on Mouth" ],
[ '😈', [ 'Emotion' ], "Smiling Face with Horns" ],
[ '👿', [ 'Emotion' ], "Angry Face with Horns" ],
[ '🧳', [ 'Object', 'Clothes' ], "Luggage" ],
[ '🎃', [ 'Object' ], "Jack-O-Lantern" ],
[ '🧵', [ 'Object', 'Clothes' ], "Thread" ],
[ '🧶', [ 'Object', 'Clothes' ], "Yarn" ],
[ '👓', [ 'Object', 'Clothes' ], "Glasses" ],
[ '🕶️', [ 'Object', 'Clothes' ], "Sunglasses" ],
[ '🥽', [ 'Object', 'Clothes' ], "Goggles" ],
[ '🥼', [ 'Object', 'Clothes' ], "Lab Coat" ],
[ '🦺', [ 'Object', 'Clothes' ], "Safety Vest" ],
[ '👔', [ 'Object', 'Clothes' ], "Necktie" ],
[ '👕', [ 'Object', 'Clothes' ], "T-Shirt" ],
[ '👖', [ 'Object', 'Clothes' ], "Jeans" ],
[ '🧣', [ 'Object', 'Clothes' ], "Scarf" ],
[ '🧤', [ 'Object', 'Clothes' ], "Gloves" ],
[ '🧥', [ 'Object', 'Clothes' ], "Coat" ],
[ '🧦', [ 'Object', 'Clothes' ], "Socks" ],
[ '👗', [ 'Object', 'Clothes' ], "Dress" ],
[ '👘', [ 'Object', 'Clothes' ], "Kimono" ],
[ '🥻', [ 'Object', 'Clothes' ], "Sari" ],
[ '🩱', [ 'Object', 'Clothes' ], "One-Piece Swimsuit" ],
[ '🩲', [ 'Object', 'Clothes' ], "Briefs" ],
[ '🩳', [ 'Object', 'Clothes' ], "Shorts" ],
[ '👙', [ 'Object', 'Clothes' ], "Bikini" ],
[ '👚', [ 'Object', 'Clothes' ], "Woman’s Clothes" ],
[ '👛', [ 'Object', 'Clothes' ], "Purse" ],
[ '👜', [ 'Object', 'Clothes' ], "Handbag" ],
[ '👝', [ 'Object', 'Clothes' ], "Clutch Bag" ],
[ '🎒', [ 'Object', 'Clothes' ], "Backpack" ],
[ '👞', [ 'Object', 'Clothes' ], "Man’s Shoe" ],
[ '👟', [ 'Object', 'Clothes' ], "Running Shoe" ],
[ '🥾', [ 'Object', 'Clothes' ], "Hiking Boot" ],
[ '🥿', [ 'Object', 'Clothes' ], "Flat Shoe" ],
[ '👠', [ 'Object', 'Clothes' ], "High-Heeled Shoe" ],
[ '👡', [ 'Object', 'Clothes' ], "Woman’s Sandal" ],
[ '🩰', [ 'Object', 'Clothes' ], "Ballet Shoes" ],
[ '👢', [ 'Object', 'Clothes' ], "Woman’s Boot" ],
[ '👑', [ 'Object', 'Clothes' ], "Crown" ],
[ '👒', [ 'Object', 'Clothes' ], "Woman’s Hat" ],
[ '🎩', [ 'Object', 'Clothes' ], "Top Hat" ],
[ '🎓', [ 'Object', 'Clothes' ], "Graduation Cap" ],
[ '🧢', [ 'Object', 'Clothes' ], "Billed Cap" ],
[ '⛑️', [ 'Object', 'Clothes' ], "Rescue Worker’s Helmet" ],
[ '💄', [ 'Object', 'Clothes' ], "Lipstick" ],
[ '💍', [ 'Object', 'Clothes' ], "Ring" ],
[ '💼', [ 'Object', 'Clothes' ], "Briefcase" ],
]

function isUsed(a) {
	return a;
}

// indicate that these are used
isUsed(categories, emojis)